name: grokking_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  badges: ^3.1.2
  bloc: ^8.1.4
  code_text_field: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_code_editor: ^0.3.2
  flutter_custom_clippers: ^2.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home.png
    - assets/icons/home_normal.png
    - assets/icons/brave.png
    - assets/icons/brave_normal.png
    - assets/icons/gpt.png
    - assets/icons/gpt_normal.png
    - assets/icons/play_normal.png
    - assets/icons/myic.png
    - assets/icons/myic1.png
    - assets/profile.png
    - assets/sliverPro.jpg
    - assets/bottomAppBar/FRAME.png
    - assets/text/text.png
    - assets/bottomAppBar/appbar.png
    - assets/bottomAppBar/scaffold.png
    - assets/icons/play.png
    - assets/icons/password.png
    - assets/icons/password_normal.png
